# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: smorphet <smorphet@student.hive.fi>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/18 08:53:50 by smorphet          #+#    #+#              #
#    Updated: 2023/09/18 09:12:30 by smorphet         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = scop

SRC	= apps/main.cpp
OBJ	= $(SRC:.cpp=.o)
INC = 

CC		= c++
FLAGS	= -Wall -Wextra -Werror -pedantic
INCLUDES = -I./ -I/minilibx_opengl
LIBS = -L/minilibx_opengl-lGL -lGLEW -lglfw


all: $(NAME)

$(OBJ): $(SRC) $(INC)
	$(CC) -c $(FLAGS) $(INCLUDES) $(SRC)

$(NAME): $(OBJ)
	$(CC) $(FLAGS) $(OBJ) -o $(NAME) $(LIBS)
	@echo "\033[0;92m* $(NAME) was created *\033[0m"

clean:
	rm -rf $(OBJ)
	@echo "\033[0;91m* $(NAME) .o files were deleted *\033[0m"

fclean: clean
	rm -rf $(NAME)
	@echo "\033[0;91m* $(NAME) was deleted *\033[0m"

re: fclean all

.PHONY: all clean fclean re
.SILENT:
